/**
 * Global Variables
 */
const PROJECT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXX';
const PRIMARY_WEATHER_STATION = 'XXXX';
const SECONDARY_WEATHER_STATION = 'XXXX';
